### ISSUE TITLE
CSG.Vector3D get and set pseudo-property

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#10]
1) Sometimes it is desirable to allow access to a property that returns a dynamically computed value
or
2) you may want to reflect the status of an internal variable without requiring the use of explicit method calls.

In JavaScript, this can be accomplished with the use of a getter. It is not possible to simultaneously have a getter bound to a property and have that property actually hold a value, although it is possible to use a getter and a setter in conjunction to create a type of pseudo-property.

By definition, I don't believe that get and set of x/y/z are actually performing any optimizations. Vector3D is created with these values, which are immutable.

Where these added for a reason? Optimization?
 
Thoughts?

**Comment by kaosat-dev** [comment]
It does seem like all vec3._x & vec3.x is essentially the same , BUT it enforces immutability since only getters are defined. 
But perhaps I am misunderstanding the question , I am not entirely clear on it sorry :(

**Comment by z3dev** [comment]
But it doesn't. There's no such thing as "private" members in Javascript, so this is just a fancy way to confuse everyone.

Here's a test case. As you can see, access to a._x is possible both for get and set.

`function main() {
  var a = new CSG.Vector3D(1,2,3);
  var x1 = a.x; // access via get() x
  var x2 = a._x; // access via attribute _x
  a.x = 2; // exceptions "immutable"
  a._x = 2; // access via _x

  return CSG.cube(); // return something valid
}`

**Comment by z3dev** [comment]
Actually, the real reason for this issue is that the get/set functions confuse what Vector3D contains, i.e. x,y,z coordinates.

Also, the marshalling of these objects to/from anonymous objects now becomes complex, i.e. special code is required to convert '_x' to/from 'x'.

**Comment by z3dev** [comment]
I would also guess that there's a performance hit as well.

**Comment by z3dev** [comment]
FYI, the plan is to implement Vector3D as an array[3], use the getter and setter functions to control access (immutable), and create some performance tests. If....

**Comment by kaosat-dev** [comment]
I agree with using arrays in general for most vector ops/ underlying data structures, actually using typed arrays is even better : more performant, "compatible with GPU" etc .
The main vector & matrix libraries I use in almost all my projects are using the same :
https://github.com/stackgl/gl-vec3
https://github.com/stackgl/gl-mat4

**Comment by z3dev** [comment]
Any performance comparisons for array versus attributes versus others? I think that would be the final determination.

**Comment by z3dev** [comment]
The stackgl objects looks good by the license sucks. I'm not sure that those are worth the effort the hassle. Please let me know if you feel different as I'm an old duffer.

Anyway, we could definitely build a similar class built upon those.

**Comment by z3dev** [comment]
V2 implementation remove the need for get/set methods, following GL-MATRIX.

Closing this issue.
