### ISSUE TITLE
Support character padding for vector_text

### ISSUE THREAD

**Issue by jonsadka** [jscad/csg.js#100]
Wondering what we think about adding support for padding between characters in `vector_text`? 

Sometimes when the text is scaled down using `CGS.scale(1 / n)`, the thickness of the character will not scale down with it and thus the use of an optional padding would be useful. I'd imagine it would be something like this:
```javascript
function vector_text (x, y, string, padding = {}) {
  const {right, bottom} = padding
  let output = []
  let x0 = x
  for (let i = 0; i < string.length; i++) {
    let char = string.charAt(i)
    if (char === '\n') {
      x = x0 - (i + 1) * right; y -= (30 + bottom)
    } else {
      let d = vector_char(x + i * right, y, char)
      x += d.width
      output = output.concat(d.segments)
    }
  }
  return output
}
```

Without padding, text scaled to 1/8
![screen shot 2018-04-15 at 8 15 49 pm](https://user-images.githubusercontent.com/6504944/38788669-ede8b118-40e9-11e8-84c9-3911a8c5f336.png)

With bottom and right padding of 2, text scaled to 1.8
![screen shot 2018-04-15 at 8 15 30 pm](https://user-images.githubusercontent.com/6504944/38788673-f05e7540-40e9-11e8-819a-827a2a6471b0.png)

**Comment by lautr3k** [comment]
Comming soon with PR #107

**Comment by z3dev** [comment]
Done as part of #107
