### ISSUE TITLE
Self-documenting Comments

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#11]
I ran into JSDOC last week, and decided to try generating documentation from the comments in the code. The results were really good, with full explanations for constructors, parameters, return values, and examples. And the README can be integrated into the documentation as well.

Very impressed.

I'd like to propose a shift to use JSDOC, which means a slow migration to the comment styles in the code. I think this will improve not only user documentation, but also allow others to understand this library quickly.

http://usejsdoc.org

**Comment by kaosat-dev** [comment]
JSDOC is great, I use it regularly, so no complaints from me ! 
Also agree with the progressive migration of comment style ! Go go !

**Comment by apla** [comment]
I've converted some comments to JSDoc format while preparing autocompletion. You can see first attempt here: https://github.com/apla/csg.js/commit/e3a9a65add9c26b0e5b206ff4439ee65d612bc24

My workflow: 
 1. parse comments;
 2. get function and methods description along with available parameters
 3. generate autocompletion data

**Comment by z3dev** [comment]
@apla Awesome!

I have a whole set of changes for JSDOC to commit this weekend. Please postpone further changes as I see some duplicity already.

Where are we going to put the documentation? Maybe we can ask @Spiritdude to house the auto-generated documentation on the openjscad.org website, i.e. API.

**Comment by apla** [comment]
@z3dev then I'll focus on documenting `openscad.js` functions. I'm not really need the document with methods description, my first goal is to make working procedure to export machine-readable autocompletion objects.

**Comment by z3dev** [comment]
@apla @kaosat-dev Please review the PR #13 for the changes to in-line documentation. These are full JSDOC comments, with parameters, returns, default values, etc.

Cheers

**Comment by kaosat-dev** [comment]
PR #13 is now merged !

**Comment by dav-m85** [comment]
@z3dev can this issue be closed ?

**Comment by z3dev** [comment]
Sure.
