### ISSUE TITLE
How to render csg code in the browser?

### ISSUE THREAD

**Issue by roipoussiere** [jscad/csg.js#124]
First, sorry to post my question here, I don't have a Google+ account.

There are a many things not very clear for me. I just want to display a simple 3d-model in my browser.

Using [evanw's csg.js](https://github.com/evanw/csg.js) implementation, I can do this (this is a minimal working example of its [documentation page](https://evanw.github.io/csg.js/)):

```html
<!DOCTYPE html>
<html><head>
  <script src="lightgl.js"></script>
  <script src="csg.js"></script>
  <script src="viewer.js"></script>
</head><body>
<div id="0" class="viewer"></div>
<script>
  var cube = CSG.cube({ center: [-0.25, -0.25, -0.25] });
  var sphere = CSG.sphere({ radius: 1.3, center: [0.25, 0.25, 0.25] });
  var myCsg = cube.subtract(sphere);
  addViewer(new Viewer(myCsg, 200, 200, 6));
</script>
</body></html>
```

...this works pretty well:

![image](https://user-images.githubusercontent.com/1665542/47042531-cb85c100-d18b-11e8-9665-c5e9862e4ded.png)

Since evanw's csg.js seems no longer maintained (no changes in 6 years), I would like to do the same thing with jscad's csg.js, which is, if [I understand well](https://github.com/jscad/csg.js/blob/master/csg.js#L14), a fork of evanw's work (I suppose that Jscad organization is a new maintainer in some way, but I'm not sure).

Note that I don't want to work specifically with lightGL, three.js or other libraries are fine if you use an other.

The problem is that jscad's csg.js uses node, with `require()` statements, so I can't use it easily as `<script src="csg.js"></script>`.

I noticed in [your npm repo that you used browserify](https://www.npmjs.com/package/@jscad/core#acknowledgements) in some way, so I think you have a solution but I don't get it.

**How to render csg code in the browser?**

If it's only a lack of documentation I can work on it after some explanations, if you think it's relevant.

**Comment by danmarshall** [comment]
This may or may not help, but take a look at my project which lets you create your own gallery: 
source: https://github.com/danmarshall/jscad-gallery
demo: https://danmarshall.github.io/jscad-gallery/

You can fork it and immediately have a site to show 3d designs, then cutomize the site any way you like.

**Comment by roipoussiere** [comment]
@danmarshall Thanks. I see that you use [ui.js](https://github.com/danmarshall/jscad-gallery/blob/master/js/ui.js) and [jscad-viewer.js](https://github.com/danmarshall/jscad-gallery/blob/master/js/jscad-viewer.js). This last is about 10k lines long. What are the steps I need to do to reproduce this? Did you use browserify? What are the parts of these files you written yourself?

@z3dev @pentacular any idea?

**Comment by pentacular** [comment]
Do you want to compute the model in the browser or just display it there?

**Comment by roipoussiere** [comment]
> Do you want to compute the model in the browser or just display it there?

Compute it, I think. I would like to describe my model in JS files, then let the user play with some inputs to update it dynamically.

**Comment by danmarshall** [comment]
Yes I used browserify. The source files of the viewer are here:
https://github.com/jscad/OpenJSCAD.org/tree/master/packages/web/src/ui/viewer

The browserify command I used is here:
https://github.com/danmarshall/jscad-gallery/blob/master/package.json#L12

Again, it might be very easy if you just fork my repo, if this is the functionality you want:
https://danmarshall.github.io/jscad-gallery/jscad-rimbox

![image](https://user-images.githubusercontent.com/11507384/54323970-cdc43e00-45b8-11e9-8f80-3baaacb820f4.png)

**Comment by roipoussiere** [comment]
Thank you for these instructions @danmarshall!
