### ISSUE TITLE
union / intersection has rounding issues

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#137]
This simple example shows that union / intersection suffer from small rounding in values.

```
function main () {
    var c1 = cube({size: [44, 26, 5.0], center: true});
    c1 = c1.translate([0,0,-1.25]); // change to correct error
    var c1bounds = c1.getBounds();
    
    var c3 = cube({size: [44, 26, 1.8], center: true}); // change to correct error
    var c3bounds = c3.getBounds();
    
    var z = c1bounds[0].z - c3.getBounds()[1].z;
    console.log(z);
    c3 = c3.translate([0,0,z-0.000001]); // change to 0.1 to see effect on union
    var c3translate = c3.getBounds();
    
    console.log(c1bounds[0]);
    console.log(c3bounds[1]);
    console.log(c3translate[1]);

    var c1c2c3 = union(
        c1,
        c3
    );
    return c1c2c3.intersect(cube({size: 100, center: true}).translate([0, 50, 0]));
}
```

**Comment by z3dev** [comment]
Shorter version.

```
function main () {
    var c1 = CSG.cube({radius: [22, 13, 2.5], center: [0,0,-1]});
    var c3 = CSG.cube({radius: [22, 13, 0.9], center: [0,0,-4.4]});
    var c4 = CSG.cube({radius: [50,50,50], center: [0,50,0]});

    var c1c3 = union(c1,c3);
    return c1c3.intersect(c4);
}
```

**Comment by z3dev** [comment]
There seems to be an issue with mayOverlap(), as this union(c1,c3) is returning a combined geometry with ALL polygons from c1 and c3. I checked... mayOverlap() is returning 'false'.

```
    var overlaps = c1.mayOverlap(c3);
    console.log(overlaps);
    console.log(c1.getBounds());
    console.log(c3.getBounds());
```

**Comment by kaosat-dev** [comment]
but is that not coherent ?
if I do a union of disjointed (non overlapping) shapes , I would expect the union to contain all the polygons of both

**Comment by z3dev** [comment]
Not in this case. c1 and c3 actually meet at Z = -3.5 but there's a rounding issue, which results in comparing -3.5 and -3.500000004. mayOverlap is just for optimization, but in this case the extra polygons cause intersection to fail.

**Comment by kaosat-dev** [comment]
ahh ok that makes it a lot clearer, sorry !

**Comment by z3dev** [comment]
![issue137](https://user-images.githubusercontent.com/8969165/56647218-0ed16700-66bc-11e9-8a0a-34e51ed3edf2.png)

**Comment by z3dev** [comment]
No problem. This only uncovered an issue in mayOverlap() function. I'm sure there are other precision issues. :(

**Comment by DanielJoyce** [comment]
Should just switch to integer math. ;)

**Comment by z3dev** [comment]
the issues in mayOverlap() have been resolved and tested in V2
