### ISSUE TITLE
rewite fuzzy factories

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#139]
Fuzzy Factories are really inefficient, and could be a cause of issues in solids.

The current versions of the fuzzy factories:
- converts numbers to strings for hash values '99999/99999/9999'
- creates two (2) hash values to 'correct' rounding issues
- uses object attributes for storing points by hash values
- looks up stored points by hash, which is basically just full traversals
- uses EPS as a numeric tolerence, does really compare distances between points
- uses the same logic for looking up planes, which is just WRONG due to the precision required for normals
- mixes planes (normals) and points from unrelated polygons, which could lead to all kinds of issues

REWORK Option 1 : Reuse Points within EPS distance
- rework the logic to use a simple map of points
- compare the distance between points
- reuse points from the map if distance < EPS
- if a point is reused then always calculate a new plane

REWORK Option 2 : Round All Points
- define a tolerence for all points
- round all points to the tolerence
- always calcuate a new plane

**Comment by kaosat-dev** [comment]
Great clear points @z3dev !
Is this a list of ideas options AFTER your current PR fixing things ? or complimentary ?

**Comment by z3dev** [comment]
I didn’t change anything in the PR #138 . I didn’t want to break everything.
This issue is for later persual.

**Comment by z3dev** [comment]
Notes from reviews:
- geom3/cannonalize will also need changes, possibly elimination if possible

**Comment by pentacular** [comment]
Definitely option 2, else you'll end up with accumulated error.

I was just thinking of doing that to make geom2 tests reasonable.

**Comment by DanielJoyce** [comment]
Cannonalize is a typo. The real word is canonicalize.

**Comment by z3dev** [comment]
V2 eliminates fuzzy factories.

Closing this issue.
