### ISSUE TITLE
I tried to get the cross section of a 3D object, but it seemed wrong.

### ISSUE THREAD

**Issue by hurryhuang1007** [jscad/csg.js#140]
I created a tetrahedron and used a plane to intercept it. But there seems to be an additional bounding box in the result.

the dome: [![Edit p9o6wzlzrq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p9o6wzlzrq)

in my project like this: 
![image](https://user-images.githubusercontent.com/21291247/51825110-08cb2480-231f-11e9-940f-1dde41c478fb.png)

**Comment by z3dev** [comment]
@hurryhuang1007 thanks for the information.

Can you supply a quick code snippet?
There are several ways to get the cross section. I want to know the functions being used.

**Comment by hurryhuang1007** [comment]
@z3dev The code in the demo that I posted was my implementation in my project

**Comment by hurryhuang1007** [comment]
@z3dev the “edit on code sandbox” is a link

**Comment by hurryhuang1007** [comment]
@z3dev Excuse me, can u tell me is it I used the wrong API or it was a bug?

**Comment by z3dev** [comment]
The tetrahedron seems to be created with opposing faces, so I reversed the face definitions to create a valid solid.
`
let faces = [[0, 1, 2], [0, 3, 1], [0, 2, 3], [1, 3, 2]];
`
Now, the section cut seems to work, but results in some rotation issues due to the basis.

**Comment by hurryhuang1007** [comment]
yeah, thx for ur answer, it's work.
But I don't understand the difference define faces by `[[0, 1, 2], [0, 3, 1], [0, 2, 3], [1, 3, 2]]` or `[[0, 1, 3], [0, 2, 1], [0, 3, 2], [1, 2, 3]]` .
Should there be a difference?

**Comment by z3dev** [comment]
@hurryhuang1007 Please close if satisfied. Thanks.

**Comment by hurryhuang1007** [comment]
very thx, I close it now.
