### ISSUE TITLE
V2 : Paths Discussion

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#143]
### Currently: V1 Path Object
- object API requiring new
- each method call creates a new path from this.ponts + new points
- each method call discards original options, i.e. control points, etc.
- no function to obtain evenly spaced points on (useful a LOT OF TIMES)
- no notion of direction (outside/inside)

**Path2 Methods:**
- Path([points], boolean) // boolean: is closed?
- appendPoint(point)
- appendPoints([points])
- appendArc(point, options)
- appendBezier(point, options)
- close()
- concat(path)

Notes:
- All functions are append TO a specific point.

**Example:**
```
let path = new CSG.Path2D([[20, -20], [20, -30]])
path = path.appendArc([50,-10],{xradius: 15, yradius: -20, xaxisrotation: 0, clockwise: false, large: false})
path = path.appendPoint([10, -10])
path = path.close()
let shape = path.innerToCAG()
```
Notes:
- Each function appends a set of points to the exiting path (points), and returns a new path (and set of points).
- There are no options when converting to a 2D shape.

### Future: V2 path2 functional
- functional API, plus new transform functions (rotate, translate, scale, etc)
- separation of concerns : functional API separated from geometry / generation
- each function call creates new shapes (path2) from the previous shape
- each function call discards original options, i.e. control points, etc.
- shape consists of geometry and properties
- geometry (path) consists of
  - list of 3D points, with Z clampled to 0 (in support of future 3D path functionality)
  - transform
  - state (isClosed)

**Curve Types:**
- line : start, end
- arc : start, center, radius, startAngle, endAngle
- quadratic bezier: start, controlPoint1, controlPoint2
- cubic bezier: start, controlPoint1, controlPoint2, end

**API Functions:**
- fromPointArray(options, ...points) → path2 (NEW)
- appendPoint(options, point, path2) → path2
- canonicalize(path2) → path2 (**DROP?**)
- close(path2) → path2
- concat(...path2) → path2
- eachPoint(options, function, path2) --- calls thunk once for each point
- equals(a, b) → boolean
- reverse(path2) → path2 [left and right sides swapped]
- toPointArray(options, path2) → Point Array
- transform(path) → path2 (NEW)

Aliases to Functions:
- fromPoints(options, ...points) → fromPointArray(options, ...points) → path2
- appendArc(options, point) → appendPoint(options, point, path2) → path2
- appendBezier(options, point) → appendPoint(options, point, path2) → path2
- rotate() → transform(path) → path2 (NEW)
- translate() → transform(path) → path2 (NEW)
- scale() → transform(path) → path2 (NEW)

Example:
```
let path = path2.fromPointArray({}, [[20, 20]])
path = path2.appendPoint({}, [20, -30])
path = path2.appendArc({...}, path)
path = path2.appendPoint([10, -10], path)
let shape = shape2.fromPoints(path2.toPointArray({close: true}, path))
```
Notes:
- The

**Geometry Functions:**
- fromPointArray({ closed = false }, ...vec2) → path
- appendPoint(options, point, path) → path
- canonicalize(path) → path <- probably should be an internal interface
- close(path) → path
- concat(...path) → a concatenated path
- eachPoint(options, function, path) --- calls thunk once for each point
- equals(a, b) → boolean <- uncertain this is useful for more than tests
- reverse(path) → path [left and right sides swapped]
- toPointArray(options, path) → Point Array
- transform(path) → path (NEW)

### Related Issues:
#16 #68 #84

### TBD for Later Versions
- descriptive API : data describes each path segment/curve that makes up a complex 2D shape
- lazy conversions: convert to geometry only when necessary, i.e. for conversions to points

**Comment by kaosat-dev** [comment]
Great summary, I will add the other points today.
2d and 3d paths are different, but it is mostly the 2 vs 3 components of their points that change.
- curve types can be simple arrays
[p1,p2] 
[p1, p2 , ctrl1]
[p1, p2 , ctrl1, ctrl2]

**Comment by z3dev** [comment]
Those were for your notes. 😃

**Comment by z3dev** [comment]
@kaosat-dev please revise the initial comment for any missing information/points. i hope this helps solidify the design of path2.

**Comment by pentacular** [comment]
Either I misunderstand or there are some errors in the V1 summary.

* accumulates a list of points instead of returning new objects

You can see that it returns new objects, as here:
https://github.com/jscad/csg.js/blob/master/src/core/math/Path2.js#L133

* each function call discards all options provided, i.e. control points, etc.

You can see that it extracts the options provided, such as control points, here:
https://github.com/jscad/csg.js/blob/master/src/core/math/Path2.js#L275

* difficult to convert to 2D and 3D shapes

A bit confused by this. These functions may not have the best names, but they're easy to use.

path.innerToCAG() and path.expandToCAG()

* no function to obtain evenly spaced points on (useful a LOT OF TIMES)

That's true, but you almost never want evenly spaced points, because they'll end up cutting across corners.

What I put together for my own use was a path iterator, which allows you to advance along a path by a certain amount, and to tell you how far you can advance to the next corner.

This allows me to take a path and rebuild it as a path of suitable stitch lengths for embroidery.

* no notion of direction (outside/inside)

Paths are directional in that the points are ordered, from this you can apply winding rules.

However, this isn't respected by innerToCAG() which uses CAG.fromPoints which ignores winding.

**Comment by pentacular** [comment]
Regarding the suggested V2 api, I see a few problems.

let path = path2.line([[20, 20], [20, -30]])

A line does not have direction, and using line as a constructor means that every other kind of segment needs to be a constructor, which doubles the interface size.

Let's be consistent with other geometries, and use a from method as a constructor, providing an origin.

e.g. path = fromPoint(x, y)

path = arcTo(options, path)

This reverses the verbNoun convention, append seems clearer.

path = appendPoint(point, path)

A path is really a sequence of way points, so this fits nicely.

But to express curves between those way points we can add options.

e.g., path = appendPoint({ how to get there }, next waypoint, path to extend)

let shape = shape2.fromPoints(path2.toPoints({segments: 32, close: true}, path))

Resegmenting a path to a fixed number of even segments is going to be something that is almost always the wrong thing.

But if we can transform the path to an array of points, then we can transform it to a suitable segmentation, considering how we need to handle corners.

So I suggest

fromPoint(point)
appendPoint(options, point, path)
toPointArray(path)
reverse(path)

to handle the above cases

**Comment by z3dev** [comment]
Great. Thanks.
Updated sligthly, moving to verbNoun functions.

From the user view point, appendArc / appendBezier may be easier to understand then appendPoint({options}). But general support for curved segments would be a good addition.

**Comment by pentacular** [comment]
Sure, user API should add whatever's convenient for humans.

But I hope that can translate into options and point for appendPoint at the geometry level. :)

**Comment by pentacular** [comment]
How about dividing between geometry and user apis like so:

Geometry API
* fromPointArray({ closed = false }, ...vec2) → path
* appendPoint(options, point, path) → path
* canonicalize(path) → path <- probably should be an internal interface
* close(path) → path
* concat(...path) → a concatenated path
* eachPoint(options, function, path) --- calls thunk once for each point
* equals(a, b) → boolean <- uncertain this is useful for more than tests
* reverse(path) → path [left and right sides swapped]
* toPointArray(options, path) → Point Array
* transform(path) → path (NEW)

User api

* appendArc(options, point) → appendPoint(options, point, path) → path
* appendBezier(options, point) → appendPoint(options, point, path) → path
* translate
* rotate
* appendPoints
* etc
