### ISSUE TITLE
V2: Split into Specialized Functions / Modules

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#154]
Split the current library into more specialised functions / modules with clean and simple interfaces. Each 'module' should be a useful building block in other forms of geometry, API interface, librariy, and/or application.

Split:
- [x] math : objects for pure mathematical operations
  - line2, line3, mat4, orthonormalbasis, plane, vec2, vec3, vec4, and required utils / constants
- [ ] colors : special API for obtaining color definitions and color conversions
- [ ] geometry : objects for managing geometries (JSCAD V2 implementations)
  - path, geom2, geom3, poly3, required utils / constants
- [ ] api : general API for users, with conversion and checks of parameters
- [ ] generations : geometry generation for paths, shapes, etc
- [ ] operations : specialzed operations on geometry
  - [ ] booleans
  - [ ] transforms
  - [ ] extrusions
- [ ] cnc : special API for CNC designs
- [ ] scad : special API for those coverting from OpenSCAD

**Comment by pentacular** [comment]
Suggest major divisions as

algorithms
  (e.g., extrusion)
  (e.g., color-conversion)
api
  v1
  v2
math
geometry

Given that color needs to survive union, and algorithmic processing, I think it needs to be a property of poly3 / vec3

Hopefully color conversions can be under algorithms.

**Comment by pentacular** [comment]
Ah, I failed at formatting.

I mean.

api/v1/...
api/v1/path/...
api/v2/...
api/v2/extrusion-ops/...
api/scad/...

etc.
