### ISSUE TITLE
swept volume of a solid following a path

### ISSUE THREAD

**Issue by gabrielandreussi** [jscad/csg.js#161]
Hello,
I would like to know if there is a way to swept a solid into a path.
I managed to find a result by transforming a solid into polygons and extruding them, but the result is slow and can only be done for linear extrusions.
Example image attached
Solid:
![2](https://user-images.githubusercontent.com/38664555/54156710-91140d80-4425-11e9-886b-0b5ba4473c70.png)
Swept volume result:
![1](https://user-images.githubusercontent.com/38664555/54156733-9cffcf80-4425-11e9-81c0-d58d0ad9551d.png)

I would be happy if there is a solution for this, or if you are thinking about developing something
Thanks

**Comment by z3dev** [comment]
I think this would be possible using 3D hull, as the swept would be the hulling of two identical shapes.

Thoughts?

**Comment by RedHatter** [comment]
That would be true for the simple example shown above but 3D hull would not work for more complex situations. For example if the path is a curve. It could be approximated by placing identical objects at intervals along the curve but, not only would that be a pain to do, it wouldn't produce any true curves.

**Comment by z3dev** [comment]
@gabrielandreussi Please see the examples for V2 JSCAD. There have been improvements to extruding, including extruding while following a path in 3D space.

www.openjscad.xyz
