### ISSUE TITLE
Feature Request:  Polygon is self intersecting! error message should show details

### ISSUE THREAD

**Issue by WolfgangFahl** [jscad/csg.js#162]
Currently the error is created like this:
 ```
if (isSelfIntersecting(result)) {
    throw new Error('Polygon is self intersecting!')
}
```

and the issue is only shown by some magic debug which can be switched on in the console
```
if (doLinesIntersect(side0[0], side0[1], side1[0], side1[1])) {
        if (debug) { console.log('side ' + i + ': ' + side0); console.log('side ' + ii + ': ' + side1) }
        return true
      }
```

since there is only one pair of points that causes the issue the information about the pair of points could be part of the error message and would be a major improvement in finding the culprit for such an issue e.g. when importing svg files.

**Comment by z3dev** [comment]
@WolfgangFahl This issue will not be fixed as part of this library, which is obsolete now.

If this is an issue inside the modeling library of OpenJSCAD.org then this can be fixed, but I believe this check is no longer performed.

If satisfied then please close this issue.

**Comment by z3dev** [comment]
This will not be fixed. Please reopen issues at OpenJSCAD.org
