### ISSUE TITLE
Issue with core Matrix4x4.translation function

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#17]
_From @rasmuskr on April 27, 2016 22:9_

Hey

I am pretty sure that the function CSG.Matrix4x4.translation is broken from:
https://github.com/Spiritdude/OpenJSCAD.org/blob/master/csg.js#L3586

```
// Create an affine matrix for translation:
    CSG.Matrix4x4.translation = function(v) {
        // parse as CSG.Vector3D, so we can pass an array or a CSG.Vector3D
        var vec = new CSG.Vector3D(v);
        var els = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, vec.x, vec.y, vec.z, 1];
        return new CSG.Matrix4x4(els);
    };
```

The matrix should look like this

```
var els = [1, 0, 0, vec.x, 0, 1, 0, vec.y, 0, 0, 1, vec.z, 0, 0, 0, 1];
```

I may fix this and open a PR but dont have the tools at the computer I am currently on.

_Copied from original issue: Spiritdude/OpenJSCAD.org#148_

**Comment by z3dev** [comment]
@rasmuskr Can you open an issue against CSG.js at the following repository? That's the original repository and you'll get faster answers there.

https://github.com/joostn/OpenJsCad

**Comment by kaosat-dev** [comment]
Should it actually not be dealt with here @z3dev  (so the your last comment change to reflect this ?)

**Comment by z3dev** [comment]
The tool brought my original comment with this issue. I believe that this is the new home of CSG.js.

Would this be better under another repository?

**Comment by kaosat-dev** [comment]
No not that is ok , this makes sense in this repo, I just was not sure if the comment was part of the 'migrated' texts :)

**Comment by z3dev** [comment]
Understood. Definitely hard to tell if the comment was original or transferred via the tool. Going forward, i'll add a small comment to the bottom of transferred issues.

**Comment by z3dev** [comment]
V1 Matrix4x4.translation() and V2 mat4.fromTranslation() are the same, and correct.

The original request may have confused a matrix for translation VERSUS the matrix math translate by a vertex.

I'm closing this.
