### ISSUE TITLE
Did there used to be a layFlat() method?

### ISSUE THREAD

**Issue by BarbourSmith** [jscad/csg.js#186]
I vaguely remember that in the distant past there was a layFlat() method, but now I can't find any trace of it. Did that exist once, and does it still?

This is a question and not an issue. All is well.

Thanks!

**Comment by z3dev** [comment]
Well... yes. It’s a horrible beast of a function.

Wouldn’t you be better off just rotating and translating into position?

P.S. V2 CAG will not include this. We hope someone will step up and create a better way.

**Comment by z3dev** [comment]
It’s a method on CSG called lieFlat()

**Comment by BarbourSmith** [comment]
😛 I was hoping there was a way to do it that wouldn't be a horrible beast of a function. Thanks for the advice, I look for another way
