### ISSUE TITLE
api.md useless without context

### ISSUE THREAD

**Issue by volconst** [jscad/csg.js#196]
Hello,
I am trying to learn how to use the project to design parts, so I opened https://github.com/jscad/csg.js/blob/V2/docs/api.md to get an overview of available functions.
The documentation is just a list of functions with unknown location. Even if I want to invoke some function, the documentation does not indicate what file to require to access it.

**Comment by peter-hartmann** [comment]
@volconst - agreed! I was successful in creating a project that uses ```@jscad/csg-api``` and ```@jscad/csg-viewer```.  It allows to script custom models and copy/use models created at openjscad.org.
When installing ```yarn add @jscad/csg-api``` somehow it also pulls ```@jscad/csg``` into the ```node_modules``` folder but I wasn't able to reference anything in there and used the ```@jscad/csg-api``` instead which works well, but is marked depreciated and the api is a bit different.

Anyway here is a link, perhaps it gives some pointers on how to create something useful: https://github.com/peter-hartmann/jscad-render-ts

**Comment by z3dev** [comment]
V2 API is now online and current. Documentation is being generated as part of the release process.

www.jscad.xyz/docs/

**Comment by z3dev** [comment]
This library is now part of the meta project; OpenJSCAD.org

The relevant package is now called 'modeling', and can be obtained via NPM via @jscad/modeling
In addition, the documentation is being created from the JSDOC comments in the code, which are being published to www.openscad.xyz/docs/

@volconst Let's move this discussion to OpenJSCAD.org.
