### ISSUE TITLE
Simplify the use of csj.js in the browser

### ISSUE THREAD

**Issue by lypwig** [jscad/csg.js#198]
I created the issue #124 few years ago to know how to use csg.js in the browser and got an answer.

I think it's a common use case, for instance to have a simple client-side app that allow a user to customize a 3d model. From a personal point view, it's even the core feature of csg.js, otherwise I prefer Python-based 3d library for server-side, like [cadquery](https://cadquery.readthedocs.io/en/latest/).

The fact is that using csg.js in the browser is still complicated. It could be however improved in two steps:
- provide a all-in-one vanilla-javascript library, like `csg-all.min.js`, that can be included in a html script tag, just like with [evanw's csg.js](https://evanw.github.io/csg.js/).
- add documentation on the readme on how to use this library in the browser with a simple example.

**Comment by z3dev** [comment]
This library is now part of the larger project OpenJSCAD.org
So, take a look at the projects using OpenJSCAD.org.

https://github.com/jscad/OpenJSCAD.org/network/dependents?package_id=UGFja2FnZS00NTkyMTgwODA%3D

**Comment by lypwig** [comment]
> This library is now part of the larger project OpenJSCAD.org
So, take a look at the projects using OpenJSCAD.org.

I don't understand how your comment answers the issue. I already know that this library is part of OpenJSCAD.org and there are other project that use OpenJSCAD.org, this is not the point.

**Comment by z3dev** [comment]
@roipoussiere You closed #124 a few years back after a dialogue on how to use this library. This issue seems to be the same.

There are also similar issues at OpenSCAD.org.

So, are you looking for documentation?

**Comment by lypwig** [comment]
> You closed #124 a few years back after a dialogue on how to use this library.

Yes, because the issue was a question, and someone answered this question.

This current issue is different: its not a question, it's a request. The request of simplify the use of csg.js in the browser, because even if I now how to do it, it is still complicated, although it could be really useful.

**Comment by z3dev** [comment]
How’s this for simple?

https://github.com/z3dev/vue-components

**Comment by mildred** [comment]
Not being familiar with Vue.js, I find it difficult to integrate in a javascript app I already have. My app is already creating 3D models, but I only get 2D view of them currently, and I'd like to add a 3D view too.

**Comment by z3dev** [comment]
> Not being familiar with Vue.js, I find it difficult to integrate in a javascript app I already have. My app is already creating 3D models, but I only get 2D view of them currently, and I'd like to add a 3D view too.

@mildred this library concentrates on the ‘core’ design API. For example, removing holes from a solid. The viewing of the results (2D and 3D geometry) is handled by the WEB UI. Would you like some assistance?

**Comment by z3dev** [comment]
The components found in OpenJSCAD.org have been improving, and several members of the User Group have been putting together custom applications/ websites.

The simplest application can be pieced together from the modeling package and the regl-renderer package. By downloading OpenJSCAD.org, the demo.html (application) can be opened with any browser, and the sample design can be viewed.

https://github.com/jscad/OpenJSCAD.org/tree/master/packages/utils/regl-renderer

This is the simplest application available.
