### ISSUE TITLE
V1 : Cuboid not exported

### ISSUE THREAD

**Issue by kbruneel** [jscad/csg.js#200]
Hi,

Is there a reason why cuboid is not exported here?

https://github.com/jscad/csg.js/blob/9abade05bb60387292ed66618c7623f3d100683e/csg.js#L143

Many thanks,
Karel

**Comment by z3dev** [comment]
@kbruneel welcome

Cuboid should be exported.

FYI, this library is now part of the larger project under OpenJSCAD.org repository. Under the V2 branch, this library is called ‘modeling’. If possible, I suggest that you work with V2 going forward.

**Comment by kbruneel** [comment]
Ah ok. I did not get that. 

In the modeling lib cuboid is exported correctly.

Thanks,
Karel

**Comment by z3dev** [comment]
Yes. Cuboid is part of the normal test suite now.

You can try out V2 at www.jscad.xyz

Let us know if you have any issues.
