### ISSUE TITLE
Feature Request: Support Colors on CAG Objects

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#25]
_From @z3dev on January 7, 2016 6:19_

There have been many requests for this feature on the OpenJSCAD Community as users are starting to using CAG objects to create parametric driven applications for laser cutters and CNC machines.

In addition, SVG supports colors on all paths, polygons, shapes, etc. I'm sure that DXF and other formats are the same. The conversions to and from other formats really requires colors.

As of now, only CSG and CAG objects can be exported so the critical support is for CAG.setColor()

_Copied from original issue: joostn/OpenJsCad#78_

**Comment by z3dev** [comment]
I've been thinking about this issue. Basically, colors can be supported easily, but the operations need to know what to do with colors when multiple 2D objects are unioned, subtracted, etc.

The simplest paradigm would be "inherit" the color of the primary object. So, you don't need to mess with an object with multiple polygons. The CAG object has one (1) color, period.

**Comment by kaosat-dev** [comment]
I have been scratching my head over this, and I also came to more or less the same conclusion: keeping it simple !

**Comment by z3dev** [comment]
V2 allows the setting of color for any object. All V2 geometries are now rendered with color as well.
