### ISSUE TITLE
Formats.js

### ISSUE THREAD

**Issue by danmarshall** [jscad/csg.js#27]
Hello, are you planning on also bringing in the [formats.js](https://github.com/joostn/OpenJsCad/blob/gh-pages/src/formats.js) file into this repo? This file had the export formats like *.toSTL()* that I was using.

**Comment by kaosat-dev** [comment]
@danmarshall all the formats support was rather heavilly restructured in the openjscad dev branch (https://github.com/Spiritdude/OpenJSCAD.org/tree/dev/src/io) it will be soon also be split out into a separate repo under the jscad 'umbrella' , dedicated to input & output format handling.

**Comment by danmarshall** [comment]
Thanks, looking forward to it. Do you have a rough timeline? And how do you announce when it is ready?

**Comment by kaosat-dev** [comment]
@danmarshall I hope in the next three weeks or so maximum?
As far as announcements go , we don't really have a channel for that yet, so it will just appear in the list of repositories under the jscad github repo and, under the npm namespace.

**Comment by z3dev** [comment]
We can post to the development forum for the OpenJSCAD user group. How's that?

**Comment by kaosat-dev** [comment]
@danmarshall this is now done !
you can find the new repo here https://github.com/jscad/io
The changes on the OpenJSCAD end have also been merged into dev https://github.com/Spiritdude/OpenJSCAD.org/tree/dev
