### ISSUE TITLE
Tolerances

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#29]
@joostn I'm revisiting all the hard coded tolerances in the library, and trying to make sense out of the values being applied.

I've introduced CSG.ESP = 1e-5 for the default value, but think there should be a few more tolerances available. Maybe...

CSG.distanceEPS = 1e-5
CSG.areaEPS = (CSG.distanceEPS*CSG.distanceEPS)/2;
CSG.angleEPS = 1e-3; // percent of angle

Thoughts?

**Comment by joostn** [comment]
What would you need those other tolerances for?
If i recall correctly the CSG operations need a tolarance value to decide whether a point is on a plane or not. (each CSG operation creates small errors due to rounding). So that would be just a 1D distance value.

**Comment by z3dev** [comment]
First, I would like to remove the hard code values, but there are some inconsistent values as well.

The two prevalent tolerances are:

One for deciding if points should be skipped.
```javascript
                       if (p1.distanceTo(prevp1) < 1e-5) {
```
One for deciding if planes are parallel.
```javascript
    CSG.Plane.EPSILON = 1e-5;
``` 
But there are tolerances that should be reviewed as well.
```javascript
        var sphereradius = bound[1] + 1e-4;
        if (absangledif < 1e-5) {
        if (Math.abs(area) < 1e-5) {
```

**Comment by joostn** [comment]
I see what you mean. The rounding errors are actually a tricky problem but I've never really given it much thought. The 1e-5 originates from evanw's code, probably chosen as it is large enough to certainly smash alll rounding errors.

**Comment by z3dev** [comment]
@joostn Thanks

I'll take a go at this after making a few more contributions to the test cases. I don't want to break anything in a major way.

If you would be kind enough to review the changes then I'll be happy.

**Comment by z3dev** [comment]
I created PR #31 to address these tolerances. Please review if you have time. The changes are trivial but start to make sense of the tolerances.

**Comment by z3dev** [comment]
The first version has been merged. So, I'm closing this.
