### ISSUE TITLE
DEV Branch

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#4]
Or something of the sort... Changes to the library should be made on a separate branch, reviewed, merged, tested, and released.

How about creating a 'dev' branch?

Also, there are changes in the gh-pages branch of the original repository to be reviewed and merged.

**Comment by kaosat-dev** [comment]
I am ok with creating a dev branch for now , but ideally:
- we should use semantic versioning : this way there is only one 'main' branch, and any breaking change / patch should be clearly visible with version number 
- dev tends to become the new master after a while , which is just more work

About the changes in gh-pages : I cannot keep track of all the changes (too little time), so feel free to create a PR :)
This kind of thing should be solved once this repo is really the 'goto place'

**Comment by z3dev** [comment]
I prefer versions actually, but thought that all Git lovers use branches.

Let's use versions, but that means that this library needs a starting place, i.e. Version 0 or A or Original.

**Comment by kaosat-dev** [comment]
Ok perfect ! 
I added a tagged release , so v0.1.0 is the current (base) version :) 
Closing this.
