### ISSUE TITLE
CAG canonicalized()

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#41]
A few questions on this confusing subject
- Is this really necessary?
- Do the CAG.circle(), etc producer functions create already canonicalized objects? If so, why call?
- When is canonicalized() required? After union? intersection? subtract? scale? It should only be used when necessary.

**Comment by kaosat-dev** [comment]
Honestly, I am not 100% sure, I seem to recall canonicalized() was used after certain operations, to flag geometry as 'clean' (redundant, or close to redudant vertices eliminated etc)

I wanted to first do a restructuring pass on csg.js (split CSG and CAG into seperate modules etc) to have a better overview on what's what, before delving into radical changes.

**Comment by z3dev** [comment]
V2 does not include this functionality. Closing this issue.
