### ISSUE TITLE
Performance: A possible boost to tree traversal

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#44]
http://ryanmorr.com/true-hash-maps-in-javascript/

See the discussion on the for loops... this might help eliminate unnecessary function calls when traveling the trees, etc.

**Comment by jeromew** [comment]
for reference, I add this link to a port of CSG to three.js that I found - https://gist.github.com/chandlerprall/1484619

Nothing new I guess, but it may interest you.

**Comment by jeromew** [comment]
I saw in the code that there are many "queues" and "stacks" on the hot path. I don't know if this could be a boost but https://github.com/creationix/fastqueue may be interesting to look at.

**Comment by z3dev** [comment]
Hash maps are now part of standard JavaScript, so closing.
