### ISSUE TITLE
catastrophic performance of array.reduce() operations returning CSG object

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/csg.js#55]
If you do this operation:
```javascript
arrayOfCSG.reduce((acc, cur) => acc.union(cur), new CSG())
```
even with not very complex objects, it will likely crash browser/ node
same operation done like this does not have the same issue

```javascript
result = new CSG().union(arrayOfCSG)
```

this is due to the implementation of the union operation which calls 
`.reTesselated().canonicalized()` every time

Other than re-implementing union or providing a wrapper with an option to NOT do these operations, not sure how it can be solved

**Comment by z3dev** [comment]
Definitely ugly...

Would a functional API resolve this? Maybe there should be...

function union() which only does union math
function reTesselated() which does only this math
function conacalize() which does only this math

CSG.union() that checks arguments and performs all of the above

This is what I'm thinking about all objects

**Comment by z3dev** [comment]
I guess there's only one way to know.... try it.
I think some other things will fall out as well.

We need performance tests. Damn

**Comment by z3dev** [comment]
The Boolean functions of V2 only calls reTesselate() after completing the Boolean operation, so closing this issue.
