### ISSUE TITLE
CAG expand / contract are creating degenerate CAG

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/csg.js#66]
The order of faces after these operations becomes wrong, and leads to unusable shapes afterwards (for extrude etc)

**Comment by z3dev** [comment]
@kaosat-dev do you have any quick examples? i'd like to add some tests as part of V2.

**Comment by kaosat-dev** [comment]
@z3dev hmm that is going to be very hard , this was ages ago, I can try to reproduce but I honestly do not remember how I found the issue above
