### ISSUE TITLE
Add way to convert CAG (circle, square, 2d polygon) to CSG.polygon to use for solidFromSlices()

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/csg.js#67]
Or just get rid of one off them to make things coherent ...
this is a copy from a very old todo : 
https://trello.com/b/QjlcL1xD/openjscadorg

**Comment by z3dev** [comment]
There are now two methods that do this; solidFromSlices() and CAG._toCsgWall()
We don't need both, just one great one.
We should choose one (or make a better one), and make sure it works perfectly.

**Comment by drom** [comment]
CAG object -> CSG.polygon = would be very useful feature.
