### ISSUE TITLE
Extrude shape along a 3D path

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/csg.js#68]
Because this is actually a core feature, this is a duplicate of both 
- a copy of a very old todo : https://trello.com/c/oleOR0jL/6-implement-catmull-rom-3d-splinesmooth-curve-passing-set-of-arbitrary-points-in-3d-space-and-extruding-along-it
- and https://github.com/jscad/OpenJSCAD.org/issues/298

**Comment by stuartpb** [comment]
What about just extruding a shape along the perimeter of a 2D path, a la rotateExtrude? I'm currently looking at putting together something like this using a combination of linearExtrude and rotateExtrude operations, but it'd be better if I could just define the path with some appendArc calls and then call perimeterExtrude on that path.

**Comment by z3dev** [comment]
I would hope that the extrude would follow either Path2D (a series of 2D points) or 3D points.

**Comment by stuartpb** [comment]
The thing I wanted to add that I don't see in implementations like [substack's extrude-by-path](https://github.com/substack/extrude-by-path/blob/master/index.js) is a corner-rounding implementation that would look like `rotateExtrude` on any sharp corners of a path. This is something I could more or less figure out how to do to extrude CAGs that are already compatible with rotateExtrude around a 2d path (where all the points already lie right of the Y axis, where all the rotation happens): for more complicated geometry, I start to think about how it'd generalize, and I get mixed up. (It seems like there should be a pivoting "axis of elimination" that would only create wall polygons for points on one side of it; however, I keep confusing myself about how and/or why only points with a turning radius of zero need this.)

**Comment by napter** [comment]
Was this ever completed? I see there was a commit last month called "Reorganization and upgrade of Extrusions ". If not, is there a any way to accomplish this in CSG now?

**Comment by z3dev** [comment]
The short answer is ‘no’. 

You could implement something with V1 soldFromSlices(), but there will be lots of issues as noted in the discussions by @stuartpb 

V2 has some changes which will make things easier but there will still be issues with ‘corners’. Also, we are trying to keep the ‘core’ very compact. We believe this will allow others to implement high level functionality, such as this, and share with others.

**Comment by napter** [comment]
Thanks @z3dev. Does solidFromSlices allow creating a solid from slices with a hole in it? Or must the slices be polygons with no holes?

What I want to do is take a shape with a hole in it, like a doughnut, and extrude it along a curve to create a round bevel. Is that possible with CSG?

**Comment by z3dev** [comment]
UG. Sorry but V1 solidFromSlices() requires a convex polygon. And that means NO holes.

V2 uses a new geometry called ‘slice’ which can have holes. Better but not perfect.

**Comment by z3dev** [comment]
@stuartpb 
@napter 

There are now some examples that use Bézier curves to create various shapes, including extruding a shape along a 3D curve. Please see www.jscad.xyz

**Comment by z3dev** [comment]
This is possible using extrudeFromSlices() in V2 JSCAD. There's an example as well at www.openjscad.xyz

Closing.
