### ISSUE TITLE
Implement minkowsky

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/csg.js#69]

**Comment by hg42** [comment]
I think minkowski is placing a shape at each point and invoking hull on all these.
Or in other words:
* take the points of an objects ("corner" object) as a simple cloud and translate those to all point coordinates of the main object
* every point inside the main object may be dropped during collection
* create hull of the remaining points

**Comment by z3dev** [comment]
This is duplicated in OpenJSCAD.org repository so closing.
