### ISSUE TITLE
Allow Start and Stop Angles for both circles and ellipses

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#73]
Currently, circles and ellipses are complete 360 degree forms. This enhancement would allow both start and stop angles, and control how many degrees to include.

**Comment by z3dev** [comment]
Funny but cylinder() has the following option, allowing a partial (non-360) cylinder to be created.

  let alpha = parseOptionAsFloat(options, 'sectorAngle', 360)

I think 'alpha' should be calculated from start and stop angles.

**Comment by aleung** [comment]
@z3dev I was looking for such a function to create sector of a cylinder. But I couldn't find it from API document: https://github.com/jscad/csg.js/blob/master/docs/api.md

**Comment by z3dev** [comment]
Closing as this is duplicated In OpenJscad.org
