### ISSUE TITLE
Feature request: Offset for CAG

### ISSUE THREAD

**Issue by stuartpb** [jscad/csg.js#75]
See https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#offset

**Comment by kaosat-dev** [comment]
@stuartpb is that not the same thing as expand/contract that we already have ? Or am I missing something?

**Comment by stuartpb** [comment]
First off, I didn't know those functions were implemented, because they're [not documented[(https://github.com/jscad/csg.js/blob/master/docs/api.md).

Secondly, `offset` would be a unified API function that switches between `expand` and `contract` based on the sign of the argument, as described here: https://github.com/jscad/csg.js/blob/ab8b9dff870cd6836558e3a370b8093287a5dfcc/src/api/index.js#L41 - you could also make it so `expand` and `contract` do the other function's behavior for negative values, in which case `offset` would just be a synonym for `expand` (for better discoverability when translating from OpenSCAD's vocabulary).

Thirdly, as i understand it, the current implementations don't have support for the `delta` or `chamfer` options that OpenSCAD has.

**Comment by z3dev** [comment]
This will be available in V2.
