### ISSUE TITLE
Remove Object Mutators

### ISSUE THREAD

**Issue by z3dev** [jscad/csg.js#88]
The mutator functions for adding functions to the objects is improper, and should be corrected.

https://github.com/jscad/csg.js/blob/e5b922c338f484689549b115d790a4e1a065e75e/csg.js#L178

they are evil because they are done OUTSIDE the object, so that when you directly import the 'original' objects, (CSG) they are actually missing pieces. 

- I understand these but really question the worth of this morphing of classes
- is maintaining these directly in each class difficult? Is this just being lazy?
- can JavaScript engines optimize these functions?
- how to add documentation for these?
- is this really the way objects should be "extended"?

**Comment by z3dev** [comment]
I’m in favor of COPY AND PASTE. This exposes the object API cleanly, and allows specialization if necessary.

**Comment by kaosat-dev** [comment]
I agree but would go one step further : why add methods when you can use functions ? No need to mutate or expand or inherit !

**Comment by z3dev** [comment]
Agree. Possibly only those classes that do the math need to have the methods, like Matrix4x4.

**Comment by z3dev** [comment]
V2 removes objects and mutator methods.

Closing this issue.
